# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drip.proto',
  package='',
  serialized_pb=_b('\n\ndrip.proto\"(\n\x0b\x44ripRecored\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05\x64rips\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DRIPRECORED = _descriptor.Descriptor(
  name='DripRecored',
  full_name='DripRecored',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DripRecored.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drips', full_name='DripRecored.drips', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=54,
)

DESCRIPTOR.message_types_by_name['DripRecored'] = _DRIPRECORED

DripRecored = _reflection.GeneratedProtocolMessageType('DripRecored', (_message.Message,), dict(
  DESCRIPTOR = _DRIPRECORED,
  __module__ = 'drip_pb2'
  # @@protoc_insertion_point(class_scope:DripRecored)
  ))
_sym_db.RegisterMessage(DripRecored)


# @@protoc_insertion_point(module_scope)
