# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  serialized_pb='\n\x0emessages.proto\"0\n\x04Move\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\x12\n\nlaserPower\x18\x03 \x02(\r\"1\n\x0c\x44ripRecorded\x12\r\n\x05\x64rips\x18\x01 \x02(\r\x12\x12\n\nghostDrips\x18\x02 \x01(\r\"\x1d\n\x0cSetDripCount\x12\r\n\x05\x64rips\x18\x01 \x02(\r\" \n\x0fMoveToDripCount\x12\r\n\x05\x64rips\x18\x01 \x02(\r\"\n\n\x08Identify\"\x19\n\x08SetDebug\x12\r\n\x05\x64\x65\x62ug\x18\x01 \x01(\r\"\x1b\n\tGetAdcVal\x12\x0e\n\x06\x61\x64\x63Num\x18\x01 \x02(\r\"\x1e\n\x0cReturnAdcVal\x12\x0e\n\x06\x61\x64\x63Val\x18\x01 \x02(\r\"\x11\n\x0f\x45nterBootloader\"A\n\x03IAm\x12\r\n\x05swrev\x18\x01 \x02(\t\x12\r\n\x05hwrev\x18\x02 \x02(\t\x12\n\n\x02sn\x18\x03 \x02(\t\x12\x10\n\x08\x64\x61taRate\x18\x04 \x02(\r')




_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Move.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Move.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laserPower', full_name='Move.laserPower', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=66,
)


_DRIPRECORDED = _descriptor.Descriptor(
  name='DripRecorded',
  full_name='DripRecorded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='drips', full_name='DripRecorded.drips', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ghostDrips', full_name='DripRecorded.ghostDrips', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=117,
)


_SETDRIPCOUNT = _descriptor.Descriptor(
  name='SetDripCount',
  full_name='SetDripCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='drips', full_name='SetDripCount.drips', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=119,
  serialized_end=148,
)


_MOVETODRIPCOUNT = _descriptor.Descriptor(
  name='MoveToDripCount',
  full_name='MoveToDripCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='drips', full_name='MoveToDripCount.drips', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=150,
  serialized_end=182,
)


_IDENTIFY = _descriptor.Descriptor(
  name='Identify',
  full_name='Identify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=184,
  serialized_end=194,
)


_SETDEBUG = _descriptor.Descriptor(
  name='SetDebug',
  full_name='SetDebug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='debug', full_name='SetDebug.debug', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=196,
  serialized_end=221,
)


_GETADCVAL = _descriptor.Descriptor(
  name='GetAdcVal',
  full_name='GetAdcVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adcNum', full_name='GetAdcVal.adcNum', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=223,
  serialized_end=250,
)


_RETURNADCVAL = _descriptor.Descriptor(
  name='ReturnAdcVal',
  full_name='ReturnAdcVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adcVal', full_name='ReturnAdcVal.adcVal', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=252,
  serialized_end=282,
)


_ENTERBOOTLOADER = _descriptor.Descriptor(
  name='EnterBootloader',
  full_name='EnterBootloader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=284,
  serialized_end=301,
)


_IAM = _descriptor.Descriptor(
  name='IAm',
  full_name='IAm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='swrev', full_name='IAm.swrev', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hwrev', full_name='IAm.hwrev', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sn', full_name='IAm.sn', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataRate', full_name='IAm.dataRate', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=303,
  serialized_end=368,
)

DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.message_types_by_name['DripRecorded'] = _DRIPRECORDED
DESCRIPTOR.message_types_by_name['SetDripCount'] = _SETDRIPCOUNT
DESCRIPTOR.message_types_by_name['MoveToDripCount'] = _MOVETODRIPCOUNT
DESCRIPTOR.message_types_by_name['Identify'] = _IDENTIFY
DESCRIPTOR.message_types_by_name['SetDebug'] = _SETDEBUG
DESCRIPTOR.message_types_by_name['GetAdcVal'] = _GETADCVAL
DESCRIPTOR.message_types_by_name['ReturnAdcVal'] = _RETURNADCVAL
DESCRIPTOR.message_types_by_name['EnterBootloader'] = _ENTERBOOTLOADER
DESCRIPTOR.message_types_by_name['IAm'] = _IAM

class Move(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOVE

  # @@protoc_insertion_point(class_scope:Move)

class DripRecorded(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRIPRECORDED

  # @@protoc_insertion_point(class_scope:DripRecorded)

class SetDripCount(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETDRIPCOUNT

  # @@protoc_insertion_point(class_scope:SetDripCount)

class MoveToDripCount(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOVETODRIPCOUNT

  # @@protoc_insertion_point(class_scope:MoveToDripCount)

class Identify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IDENTIFY

  # @@protoc_insertion_point(class_scope:Identify)

class SetDebug(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETDEBUG

  # @@protoc_insertion_point(class_scope:SetDebug)

class GetAdcVal(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETADCVAL

  # @@protoc_insertion_point(class_scope:GetAdcVal)

class ReturnAdcVal(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RETURNADCVAL

  # @@protoc_insertion_point(class_scope:ReturnAdcVal)

class EnterBootloader(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTERBOOTLOADER

  # @@protoc_insertion_point(class_scope:EnterBootloader)

class IAm(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IAM

  # @@protoc_insertion_point(class_scope:IAm)


# @@protoc_insertion_point(module_scope)
