/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Tue Jan 27 15:25:19 2015. */

#include "drip.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DripRecorded_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DripRecorded, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DripRecorded, drips, id, 0),
    PB_LAST_FIELD
};


