/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.2 at Wed Jan 28 10:46:55 2015. */

#include "messages.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Move_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Move, x, x, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Move, y, x, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Move, laserPower, y, 0),
    PB_LAST_FIELD
};

const pb_field_t DripRecorded_fields[2] = {
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , FIRST, DripRecorded, drips, drips, 0),
    PB_LAST_FIELD
};


