/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Wed Apr  1 09:55:24 2015. */

#include "messages.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Move_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Move, x, x, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Move, y, x, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Move, laserPower, y, 0),
    PB_LAST_FIELD
};

const pb_field_t DripRecorded_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DripRecorded, drips, drips, 0),
    PB_LAST_FIELD
};

const pb_field_t SetDripCount_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SetDripCount, drips, drips, 0),
    PB_LAST_FIELD
};

const pb_field_t MoveToDripCount_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MoveToDripCount, drips, drips, 0),
    PB_LAST_FIELD
};

const pb_field_t Identify_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t IAm_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, IAm, swrev, swrev, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, IAm, hwrev, swrev, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, IAm, sn, hwrev, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, IAm, dataRate, sn, 0),
    PB_LAST_FIELD
};

const pb_field_t Measure_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Measure, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Measure, channel, id, 0),
    PB_LAST_FIELD
};


