/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Tue Jan 27 15:25:19 2015. */

#include "move.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Move_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Move, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Move, x, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Move, y, x, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, Move, laserPower, y, 0),
    PB_LAST_FIELD
};

const pb_field_t Ack_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Ack, id, id, 0),
    PB_LAST_FIELD
};

const pb_field_t Nack_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Nack, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Nack, reason, id, 0),
    PB_LAST_FIELD
};


